### ISSUE TITLE
Upgrade to t5.4-beta-26

### ISSUE THREAD

**Issue by kaosko** [tynamo/tapestry-model#3]
Currently tests start failing if you update the dependency. @ascandroli, I'm guessing you may have attempted this already?

**Comment by ascandroli** [comment]
yes I saw it. if you remove the grid.reset() call on the List.setupRender it passes, but then you get that the internal state of the grid is shared among all the list pages.

I haven't had the time to go deeper on this but I think it could be a bug on Tapestry.

> Caused by: java.lang.NullPointerException
	at org.apache.tapestry5.corelib.components.Grid.setCurrentPage(Grid.java:600)
	at org.apache.tapestry5.corelib.components.Grid.reset(Grid.java:636)
	at org.tynamo.examples.simple.pages.List.resetGrid(List.java:83)
	at org.tynamo.examples.simple.pages.List.setupRender(List.java)

I'll take a look tonight.

**Comment by ascandroli** [comment]
This looks a lot like the description on this commit:  https://git-wip-us.apache.org/repos/asf?p=tapestry-5.git;a=commit;h=f71043e9

and is somehow related to this issue: https://issues.apache.org/jira/browse/TAP5-1689

**Comment by kaosko** [comment]
Yes, looks like setCurrentPage(1) on Grid.reset() is really unnecessary or at least should be after sortModel.clear(); (lines 636-637)

**Comment by kaosko** [comment]
Works with the latest T5 beta now but need to wait for a release, closing this.
